-- Generated by psc-make version 0.6.9.5
module Main where
import Debug.Trace ()
import Prim ()
import Prelude ()
import Debug.Trace ()
foreign import main :: forall t3. Control.Monad.Eff.Eff (trace :: Debug.Trace.Trace | t3) Prelude.Unit
